@apiUrl = http://127.0.0.1:8897
@apiToken = {{$processEnv DEVPROXY_API_TOKEN}}

GET {{apiUrl}}/proxy
Authorization: Bearer {{apiToken}}

###

POST {{apiUrl}}/proxy
Authorization: Bearer {{apiToken}}
content-type: application/json

{
  "recording": true
}

###

POST {{apiUrl}}/proxy
Authorization: Bearer {{apiToken}}
content-type: application/json

{
  "recording": false
}

###

POST {{apiUrl}}/proxy/mockRequest
Authorization: Bearer {{apiToken}}

###

POST {{apiUrl}}/proxy/stopProxy
Authorization: Bearer {{apiToken}}
